name: Build

on:
  push:
    paths:
      - 'src/**'
      - Makefile
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Build
        run: make -j -k
